# Generated by Django 3.2 on 2021-04-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='videos')),
                ('url_64encoding', models.CharField(default='/upload/videos/', max_length=2048)),
            ],
        ),
    ]
