# Generated by Django 3.2 on 2021-04-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='video',
            field=models.FileField(upload_to='videos/%y'),
        ),
    ]
