# Generated by Django 3.2 on 2021-04-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_upload_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='caption',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='upload',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
