# Generated by Django 3.2 on 2021-04-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20210415_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='url_64encoding',
        ),
    ]
