# Generated by Django 3.2 on 2021-04-17 04:01

from django.db import migrations, models
import uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_remove_upload_url_64encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='video',
            field=models.FileField(upload_to='videos', validators=[uploads.validators.validate_file_size]),
        ),
    ]
