# Generated by Django 3.2 on 2021-04-25 04:59

from django.db import migrations, models
import uploads.models
import uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_alter_upload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='video',
            field=models.FileField(upload_to=uploads.models.user_directory_path, validators=[uploads.validators.validate_file_size]),
        ),
    ]
